descriptor-schema-version: "2.7"
info:
  name: iox-aarch64-alpine
  version: latest
  description: Alpine Linux ARM with lots of extras (tcpdump, telnet, lsof, netstat, nmap, wget, etc...)
app:
  cpuarch: aarch64
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    TERM: xterm
  resources:
    cpu: "400"
    memory: "128"
    network:
    - interface-name: eth0
      ports: {}
    profile: custom
  startup:
    rootfs: rootfs.tar
    target:
    - bash
    - /idle.sh
    workdir: /root
  type: docker
